#! /bin/python

import sys
import socket
from datetime import datetime

#Define our target
if len(sys.argv) == 2:
	target = socket.gethostbyname(sys.argv[1]) #Translate hostname to IPV4

else: 
	print("Invalid amount of arguments.")
	print("Syntax: python3 scanner.py <ip>")
	


#Add A banner
print("_" * 50)
print("Scanning target"+target)
print("Time started: "+str(datetime.now()))
print("_" * 50)

try:
	for port in range(1,90): #This is where you set ranges to check
		s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
		socket.setdefaulttimeout(1)
		result = s.connect_ex((target,port)) #returns an error indicator
		if result == 0:
			print("Port {} is open".format(port))
		s.close()

except KeyboardInterrupt:
	print("\nExiting program.")
	sys.exit()
	
except socket.gaierror:
	print("Hostname could not be resolved.")  #Innteruptions
	sys.exit()
	
except socket.error:			
	print("Couldn't connect to server.")
	sys.exit()
